agent:
  name: rnn_ppo_sb3
  class: sb3_contrib.RecurrentPPO
  params:
    policy: "MlpLstmPolicy"
    env: ???
    learning_rate: ${actor_lr}
    n_steps: 128
    batch_size: 128
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    normalize_advantage: True
    ent_coef: 0.0
    vf_coef: 0.5
    max_grad_norm: 0.5
    use_sde: False
    sde_sample_freq: -1
    tensorboard_log: ???
    verbose: 1
    seed: ${seed}
    device: ${device}
    _init_setup_model: True

